### PR TITLE
77 admin module management panel

### PR DESCRIPTION
**Pull request by shinymew2**
Created module panel, should be working as expected

### CODE REVIEW

**Review by eznavy — CHANGES_REQUESTED** [review]
image
'Speichern' should be changed to (for example) 'Löschen' (same goes for the English version).

image
It would be nice if the modules were less cramped in mobile view.

Apart from that, the management panel looks good to me! :)

**Comment by hwgn** [comment]
The description could be truncated using CSS (`text-overflow: ellipsis`), you might need to set a `width` parameter for that as well

**Comment by shinymew2** [comment]
> The description could be truncated using CSS (`text-overflow: ellipsis`), you might need to set a `width` parameter for that as well

I spaced out the rows which gives a better view of the texts. What do you think, should I still short it with an overflow modification?

**Comment by eznavy** [comment]
@shinymew2 I think it looks better when the description is shortened. You could make the description truncate and extend onclick (with the description being truncated by default for smaller screen sizes).
image

**Comment by hwgn** [comment]
> @shinymew2 I think it looks better when the description is shortened. You could make the description truncate and extend onclick (with the description being truncated by default for smaller screen sizes)

Oh no, did you just implement that too? q.q

**Comment by hwgn** [comment]
I didn't implement functionality to extend the description on click though, that could still be added. Should we merge this for now and make a new issue?

**Comment by eznavy** [comment]
@hwgn 
I just tested the simple truncation you proposed to see what looks better :D

**Review by hwgn — APPROVED** [review]

**Review by eznavy — APPROVED** [review]

**Pull request merged**
