### PR TITLE
the selected theme now is the disabled button

### PR DESCRIPTION
**Pull request by danielp0505**
grafik

### CODE REVIEW

**Comment by hwgn** [comment]
Not sure this achieves the intended goal, you've just switched the buttons around. The idea was to somehow highlight the active theme as "selected" rather than "disabled" since that was deemed unintuitive.

Perhaps you could look into doing some form of negative elevation or the like, maybe vuetify has something for that?

**Comment by Resteklicken** [comment]
> Not sure this achieves the intended goal, you've just switched the buttons around. The idea was to somehow highlight the active theme as "selected" rather than "disabled" since that was deemed unintuitive.
> 
> Perhaps you could look into doing some form of negative elevation or the like, maybe vuetify has something for that?

Fully agree with this ;)

**Comment by shinymew2** [comment]
I gave the selected button a color which indicates that it is pressed

**Comment by danielp0505** [comment]
> I gave the selected button a color which indicates that it is pressed image Maybe you can find the perfect color, this is only a suggestion

grafik
Considering the disabled/grayed out button was a criticism I'd say this is better.

**Comment by shinymew2** [comment]
> > I gave the selected button a color which indicates that it is pressed image Maybe you can find the perfect color, this is only a suggestion
> 
> grafik Considering the disabled/grayed out button was a criticism I'd say this is better.

I do not think that blue fits there because the blue color is not used anywhere else on the website (as far as I know :D), but in the end its a design choice. Maybe @eznavy could give this a look

**Comment by Resteklicken** [comment]
I like the blue, at least in dark mode. I would say it's an improvement over the old version and we should run it by the stakeholder. If he insists on a color from the THM color palette we (or rather the people coming after us :smiling_imp:) can redesign.

**Comment by shinymew2** [comment]
> I like the blue, at least in dark mode. I would say it's an improvement over the old version and we should run it by the stakeholder. If he insists on a color from the THM color palette we (or rather the people coming after us 😈) can redesign.

Fair enough 😂

**Review by shinymew2 — APPROVED** [review]

**Pull request merged**
