### PR TITLE
194 redesign individual module page for desktop

### PR DESCRIPTION
**Pull request by danielp0505**
grafik
grafik

### CODE REVIEW

**Review by shinymew2 — COMMENTED** [review]
The module page looks super nice now! I really like the changes. 

---
One thing that could be improved would be the use of an icon instead of an asset (talking about the book-asset for an exercise). Also the expansion-panel with the exercises could be expanded by default.

**Comment by shinymew2** [comment]
I changed the things I proposed in my review with my last commit.

**Comment by hwgn** [comment]
image
The mobile view is currently left untouched, which is fine for now but could use some of the facelift the desktop version has, too :) Could be done in the next sprint.

**Review by hwgn — APPROVED** [review]
lgtm :)

**Review by eznavy — APPROVED** [review]
lgtm, except for this small issue:

image

As the mobile view is going to be adjusted with the next sprint anyway, I propose to postpone this issue.

**Review by shinymew2 — APPROVED** [review]

**Pull request merged**
